<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    
    <IsTestProject>false</IsTestProject>
    <DiscoverTests>false</DiscoverTests>
    <ExcludeFromTestExplorer>true</ExcludeFromTestExplorer>
    
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>

    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <TargetExt>.shared</TargetExt>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SqlInterpol.Testing.Specifications\SqlInterpol.Testing.Specifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.core" Version="2.9.3" ExcludeAssets="build;buildTransitive" />
    <PackageReference Include="xunit.assert" Version="2.9.3" ExcludeAssets="build;buildTransitive" />
  </ItemGroup>

</Project>