using SqlInterpol.Configuration;
using SqlInterpol.Dialects;

namespace SqlInterpol.Execution;

/// <summary>
/// A lightweight <see cref="ISqlContext"/> that intercepts <see cref="AddParameter"/> calls
/// to emit positional format-string placeholders (<c>{0}</c>, <c>{1}</c>, …) instead of
/// dialect-specific parameter names.
/// </summary>
/// <remarks>
/// Used exclusively by <see cref="SqlCrudTemplateCache"/> to drive the rewriter pipeline
/// at cache time. The resulting rendered SQL contains <c>{n}</c> holes that are later filled
/// by <see cref="SqlBatchTemplate.Render"/> via <c>string.Format</c> with actual parameter
/// names generated by the real <see cref="ISqlContext"/> at query-execution time.
/// </remarks>
internal sealed class SqlTemplateContext : ISqlContext
{
    private int _index;

    /// <inheritdoc />
    public ISqlDialect Dialect { get; }

    /// <inheritdoc />
    public SqlInterpolOptions Options { get; }

    /// <inheritdoc />
    public IDictionary<string, object?> Parameters { get; } = new Dictionary<string, object?>();

    /// <summary>
    /// Initializes a new <see cref="SqlTemplateContext"/> for the given dialect and options.
    /// </summary>
    /// <param name="dialect">The active SQL dialect used for identifier quoting and rendering.</param>
    /// <param name="options">The configuration options (rewriters, renderer, etc.) for the pipeline run.</param>
    public SqlTemplateContext(ISqlDialect dialect, SqlInterpolOptions options)
    {
        Dialect = dialect;
        Options = options;
    }

    /// <summary>
    /// Returns the next positional format-string placeholder (<c>{n}</c>) and advances
    /// the internal counter. The <paramref name="value"/> is intentionally ignored — actual
    /// parameter values are bound at render time, not at cache time.
    /// </summary>
    /// <param name="value">Ignored at cache time.</param>
    /// <returns>A format-string placeholder such as <c>{0}</c>, <c>{1}</c>, etc.</returns>
    public string AddParameter(object? value) => $"{{{_index++}}}";

    /// <inheritdoc />
    public void Reset() => _index = 0;
}
