// <auto-generated/>
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
        
        // For .NET 8 Preview compatibility
        public InterceptsLocationAttribute(string filePath, int line, int character)
        {
        }
    }
}