using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

#pragma warning disable RSEXPERIMENTAL002

namespace SqlInterpol.Generators;

public partial class SqlAotInterceptorGenerator
{
    private static void Emit(SourceProductionContext spc, ImmutableArray<CompileTimeQueryContext> contexts, ImmutableArray<string> dialects, Compilation compilation)
    {
        var processedInvocations = new HashSet<SyntaxNode>();
        int uniqueAppendsFound = 0;
        int uniqueEntitiesFound = 0;

        var dialectQuotes = ExtractDialectQuotes(dialects, compilation);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8019");
        sb.AppendLine("#pragma warning disable CS9251");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SqlInterpol;");
        sb.AppendLine("");
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) {}");
        sb.AppendLine("        public InterceptsLocationAttribute(string filePath, int line, int character) {}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("");
        sb.AppendLine("namespace SqlInterpol.Generators.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class AotInterceptors");
        sb.AppendLine("    {");

        int interceptorCount = 0;

        foreach (var queryContext in contexts)
        {
            if (queryContext == null) continue;

            foreach (var appendCall in queryContext.AppendCalls)
            {
                if (!processedInvocations.Add(appendCall.InvocationNode))
                    continue;

                uniqueAppendsFound++;

                var syntaxTree = appendCall.InvocationNode.SyntaxTree;
                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                string interceptorMethodName = $"Intercepted_{appendCall.MethodName}_{interceptorCount++}";

                var interceptableLocation = semanticModel.GetInterceptableLocation(appendCall.InvocationNode);
                if (interceptableLocation != null)
                {
                    var attrSyntax = interceptableLocation.GetInterceptsLocationAttributeSyntax();
                    sb.AppendLine($"        {attrSyntax}");
                }
                else
                {
                    var filePath = syntaxTree.FilePath;
                    var memberAccess = (MemberAccessExpressionSyntax)appendCall.InvocationNode.Expression;
                    var lineSpan = syntaxTree.GetLineSpan(memberAccess.Name.Span);
                    var line = lineSpan.StartLinePosition.Line + 1;
                    var character = lineSpan.StartLinePosition.Character + 1;
                    var normalizedPath = filePath.Replace("\\", "\\\\");

                    sb.AppendLine($"        [InterceptsLocation(@\"{normalizedPath}\", {line}, {character})]");
                }

                sb.AppendLine($"        public static SqlBuilder {interceptorMethodName}(this SqlBuilder builder, ref {appendCall.HandlerTypeDisplayString} handler)");
                sb.AppendLine("        {");
                sb.AppendLine("            var genDb = (ISqlGeneratorBuilder)builder;");

                var arguments = appendCall.InvocationNode.ArgumentList.Arguments;
                if (arguments.Count == 0)
                {
                    if (appendCall.MethodName == "AppendLine")
                        sb.AppendLine("            genDb.AppendSegment(new SqlInterpol.SqlSegment(SqlInterpol.SqlSegmentType.Literal, \"\\n\"));");
                    
                    sb.AppendLine("            return builder;");
                    sb.AppendLine("        }");
                    continue;
                }

                var firstArg = arguments[0].Expression;
                if (firstArg is InterpolatedStringExpressionSyntax interpolatedString)
                {
                    var analysis = AnalyzeContents(interpolatedString, queryContext);

                    if (analysis.RequiresJitFallback)
                    {
                        sb.AppendLine("            builder.Append(ref handler); // JIT Dynamic Fallback");
                        if (appendCall.MethodName == "AppendLine")
                            sb.AppendLine("            genDb.AppendSegment(new SqlInterpol.SqlSegment(SqlInterpol.SqlSegmentType.Literal, \"\\n\"));");
                        
                        sb.AppendLine("            return builder;");
                        sb.AppendLine("        }");
                        sb.AppendLine("");
                        continue;
                    }

                    sb.AppendLine("            var ctx = genDb.Context;");
                    sb.AppendLine("            var options = ctx.Options;");
                    sb.AppendLine("            var dialect = ctx.Dialect;");
                    sb.AppendLine("            string dialectKind = dialect.Kind.Value;");
                    sb.AppendLine("            var layout = options.CollectionLayout;");
                    sb.AppendLine("            int indentSize = options.IndentSize;");
                    sb.AppendLine("            bool autoAliasing = options.EntityAutoAliasing;");
                    sb.AppendLine();

                    sb.AppendLine($"            switch (dialectKind)");
                    sb.AppendLine("            {");
                    
                    var targetDialects = dialects.ToList();
                    targetDialects.Add("RUNTIME");

                    foreach (var targetDialect in targetDialects)
                    {
                        var quotes = dialectQuotes.TryGetValue(targetDialect, out var q) ? q : ("\"", "\"");
                        EmitDialectSwitchCase(sb, targetDialect, interpolatedString, queryContext, analysis, quotes);
                    }
                    sb.AppendLine("            }");
                }
                else if (firstArg is LiteralExpressionSyntax literal)
                {
                    var text = literal.Token.ValueText.Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");
                    sb.AppendLine($"            genDb.AppendSegment(new SqlInterpol.SqlSegment(SqlInterpol.SqlSegmentType.Literal, \"{text}\"));");
                }
                else
                {
                    sb.AppendLine("            builder.Append(ref handler); // JIT Dynamic Fallback");
                }

                if (appendCall.MethodName == "AppendLine")
                {
                    sb.AppendLine("            genDb.AppendSegment(new SqlInterpol.SqlSegment(SqlInterpol.SqlSegmentType.Literal, \"\\n\"));");
                }

                sb.AppendLine("            return builder;");
                sb.AppendLine("        }");
                sb.AppendLine("");
            }
            
            uniqueEntitiesFound += queryContext.Entities.Count;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("AotDiagnostics.g.cs", $@"
// <auto-generated/>
// Active AOT Target Dialects: {string.Join(", ", dialects)}
// Found {uniqueEntitiesFound} tracked db.Entity() declarations.
// Found {uniqueAppendsFound} unique Append/AppendLine calls to intercept.
");

        spc.AddSource("AotInterceptors.g.cs", sb.ToString());
    }

    private static void EmitDialectSwitchCase(StringBuilder sb, string targetDialect, InterpolatedStringExpressionSyntax interpolatedString, CompileTimeQueryContext queryContext, AotAnalysisResult analysis, (string Open, string Close) quotes)
    {
        bool isRuntime = targetDialect == "RUNTIME";

        if (isRuntime)
        {
            sb.AppendLine("                default:");
            sb.AppendLine("                {");
        }
        else
        {
            sb.AppendLine($"                case \"{targetDialect}\":");
            sb.AppendLine("                {");
        }

        int segmentIndex = 0;
        string currentSqlClause = "UNKNOWN";
        string? activeTextReplacement = null; // FIX CS8600: Nullable string type bounds
        bool expectsAlias = false;
        bool nextRequiresHorizontalSpace = false;

        string QuoteIdRaw(string id) => $"{quotes.Open}{id}{quotes.Close}";
        string QuoteEntRaw(string tbl, string? sch) => sch == null 
            ? $"{quotes.Open}{tbl}{quotes.Close}" 
            : $"{quotes.Open}{sch}{quotes.Close}.{quotes.Open}{tbl}{quotes.Close}";

        string QuoteId(string id) => isRuntime 
            ? $"dialect.QuoteIdentifier(\"{Escape(id)}\")" 
            : $"\"{Escape(QuoteIdRaw(id))}\"";

        string QuoteEnt(string tbl, string? sch) => isRuntime 
            ? $"dialect.QuoteEntityName(\"{Escape(tbl)}\", {(sch == null ? "null" : $"\"{Escape(sch)}\"")})" 
            : $"\"{Escape(QuoteEntRaw(tbl, sch))}\"";

        string QuoteVar(string varName) => isRuntime 
            ? $"dialect.QuoteIdentifier({varName})" 
            : $"(\"{Escape(quotes.Open)}\" + {varName} + \"{Escape(quotes.Close)}\")";

        StringBuilder compileTimeBuffer = new StringBuilder();

        Action flushLiteral = () =>
        {
            if (compileTimeBuffer.Length > 0)
            {
                var text = compileTimeBuffer.ToString().Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");
                sb.AppendLine($"                    genDb.AppendSegment(new SqlInterpol.SqlSegment(SqlInterpol.SqlSegmentType.Literal, \"{text}\"));");
                compileTimeBuffer.Clear();
            }
        };
        
        Action<string> appendLiteral = (text) => compileTimeBuffer.Append(text);
        Action<string> appendDynamic = (expr) =>
        {
            flushLiteral();
            sb.AppendLine($"                    genDb.AppendRaw({expr});");
        };

        var contents = interpolatedString.Contents;

        for (int i = 0; i < contents.Count; i++)
        {
            var content = contents[i];
            if (content is InterpolatedStringTextSyntax textContent2)
            {
                var rawText = textContent2.TextToken.ValueText;
                
                if (activeTextReplacement != null)
                {
                    rawText = activeTextReplacement;
                    activeTextReplacement = null;
                }

                var trimmed = rawText.TrimEnd();
                if (trimmed.EndsWith(SqlKeyword.As.Value, StringComparison.OrdinalIgnoreCase))
                {
                    if (trimmed.Length == SqlKeyword.As.Value.Length || !char.IsLetterOrDigit(trimmed[trimmed.Length - (SqlKeyword.As.Value.Length + 1)]))
                        expectsAlias = true;
                    else expectsAlias = false;
                }
                else expectsAlias = false;

                var upperText = rawText.ToUpperInvariant();
                int maxIdx = -1;
                SqlKeyword? matchedKeyword = null; // FIX CS8600: Explicit nullable keyword tracking

                foreach (var kw in SqlKeyword.AllOrdered)
                {
                    if (!kw.IsClause) continue;

                    int idx = upperText.LastIndexOf(kw.Value);
                    if (idx > maxIdx)
                    {
                        maxIdx = idx;
                        matchedKeyword = kw;
                    }
                }

                if (matchedKeyword != null)
                {
                    currentSqlClause = matchedKeyword.ClauseGroup;
                }

                bool nextIsColumns = false;
                if (i + 1 < contents.Count && contents[i + 1] is InterpolationSyntax nextHole)
                {
                    string? nextFormat = nextHole.FormatClause?.FormatStringToken.ValueText;
                    bool isEntityHole = false;

                    if (nextHole.Expression is IdentifierNameSyntax nId && queryContext.Entities.ContainsKey(nId.Identifier.Text))
                    {
                        isEntityHole = true;
                    }

                    if (isEntityHole && (string.Equals(nextFormat, "columns", StringComparison.OrdinalIgnoreCase) || (string.IsNullOrEmpty(nextFormat) && (currentSqlClause == SqlKeyword.Select.Value || currentSqlClause == SqlKeyword.Returning.Value))))
                    {
                        nextIsColumns = true;
                    }
                }

                if (nextIsColumns && rawText.EndsWith(" "))
                {
                    rawText = rawText.Substring(0, rawText.Length - 1);
                    nextRequiresHorizontalSpace = true;
                }
                else
                {
                    nextRequiresHorizontalSpace = false;
                }

                appendLiteral(rawText);
            }
            else if (content is InterpolationSyntax interpolation)
            {
                string? format = interpolation.FormatClause?.FormatStringToken.ValueText;
                
                bool isAliasHole = expectsAlias || string.Equals(format, "alias", StringComparison.OrdinalIgnoreCase);
                expectsAlias = false;

                string? propertyName = null; // FIX CS8600: Explicit nullable string conversion
                string? entityIdentifier = null; // FIX CS8600: Explicit nullable string conversion

                if (interpolation.Expression is MemberAccessExpressionSyntax holeMemberAccess &&
                    holeMemberAccess.Expression is IdentifierNameSyntax identifier &&
                    queryContext.Entities.ContainsKey(identifier.Identifier.Text))
                {
                    propertyName = holeMemberAccess.Name.Identifier.Text;
                    entityIdentifier = identifier.Identifier.Text;
                }
                else if (interpolation.Expression is InvocationExpressionSyntax inv &&
                         inv.Expression is MemberAccessExpressionSyntax invMa &&
                         invMa.Name.Identifier.Text == "Column" &&
                         invMa.Expression is IdentifierNameSyntax invIdent &&
                         queryContext.Entities.ContainsKey(invIdent.Identifier.Text) &&
                         inv.ArgumentList.Arguments.Count == 1 &&
                         inv.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax lit)
                {
                    propertyName = ((LiteralExpressionSyntax)inv.ArgumentList.Arguments[0].Expression).Token.ValueText;
                    entityIdentifier = invIdent.Identifier.Text;
                }

                if (propertyName != null && entityIdentifier != null)
                {
                    var entityDecl = queryContext.Entities[entityIdentifier];
                    
                    if (queryContext.SubqueryEntities.Contains(entityDecl.VariableName))
                    {
                        flushLiteral();
                        sb.AppendLine($"                    // AOT Mapped Property Subquery/Dynamic Fallback: {entityDecl.VariableName}");
                        sb.AppendLine($"                    genDb.AppendSegment(handler.GetSegment({segmentIndex}));");
                        segmentIndex++;
                        continue; 
                    }

                    if (analysis.InlinePropertyAliases.TryGetValue(i, out var propAlias) && string.IsNullOrEmpty(format))
                    {
                        if (analysis.ReplacementForNextText.TryGetValue(i, out var rep))
                            activeTextReplacement = rep; 
                    }

                    var colMap = entityDecl.Columns.FirstOrDefault(c => c.PropertyName == propertyName);
                    var columnName = colMap != null ? colMap.ColumnName : propertyName;
                    
                    string wasAuto = entityDecl.WasAutoAliased.ToString().ToLower();

                    if (isAliasHole)
                    {
                        sb.AppendLine($"                    // AOT Mapped Property Alias: {propertyName}");
                        if (isRuntime) appendDynamic(QuoteId(propertyName));
                        else appendLiteral(QuoteIdRaw(propertyName));
                    }
                    else if (currentSqlClause == SqlKeyword.Insert.Value)
                    {
                        sb.AppendLine($"                    // AOT Mapped Property (Unprefixed): {entityDecl.VariableName}.{propertyName} -> {columnName}");
                        if (isRuntime) appendDynamic(QuoteId(columnName));
                        else appendLiteral(QuoteIdRaw(columnName));
                    }
                    else
                    {
                        sb.AppendLine($"                    // AOT Mapped Property: {entityDecl.VariableName}.{propertyName} -> {columnName}");
                        
                        if (analysis.InlineAliases.TryGetValue(entityDecl.VariableName, out var inlineAlias))
                        {
                            if (isRuntime) appendDynamic($"{QuoteId(inlineAlias)} + \".\" + {QuoteId(columnName)}");
                            else appendLiteral($"{QuoteIdRaw(inlineAlias)}.{QuoteIdRaw(columnName)}");
                        }
                        else
                        {
                            flushLiteral();
                            sb.AppendLine($"                    bool suppressAutoAlias_{segmentIndex} = {analysis.IsDmlQuery.ToString().ToLower()} && {wasAuto};");
                            sb.AppendLine($"                    string resolvedAlias_{segmentIndex} = suppressAutoAlias_{segmentIndex} ? \"\" : genDb.ResolveAlias(\"{Escape(entityDecl.VariableName)}\", \"\", {wasAuto});");
                            
                            sb.AppendLine($"                    if (!string.IsNullOrEmpty(resolvedAlias_{segmentIndex}))");
                            sb.AppendLine($"                    {{");
                            if (isRuntime) sb.AppendLine($"                        genDb.AppendRaw({QuoteVar($"resolvedAlias_{segmentIndex}")} + \".\");");
                            else sb.AppendLine($"                        genDb.AppendRaw(\"{Escape(quotes.Open)}\" + resolvedAlias_{segmentIndex} + \"{Escape(quotes.Close)}.\");");
                            sb.AppendLine($"                    }}");
                            sb.AppendLine($"                    else");
                            sb.AppendLine($"                    {{");
                            if (isRuntime) sb.AppendLine($"                        genDb.AppendRaw({QuoteEnt(entityDecl.MappedTableName, entityDecl.MappedSchemaName)} + \".\");");
                            else sb.AppendLine($"                        genDb.AppendRaw({QuoteEnt(entityDecl.MappedTableName, entityDecl.MappedSchemaName)} + \".\");");
                            sb.AppendLine($"                    }}");
                            
                            if (isRuntime) sb.AppendLine($"                    genDb.AppendRaw({QuoteId(columnName)});");
                            else sb.AppendLine($"                    genDb.AppendRaw({QuoteId(columnName)});");
                        }
                    }
                    
                    if (analysis.InlinePropertyAliases.TryGetValue(i, out var pAlias) && string.IsNullOrEmpty(format))
                    {
                        if (isRuntime) appendDynamic($"\" {SqlKeyword.As.Value} \" + {QuoteId(pAlias)}");
                        else appendLiteral($" {SqlKeyword.As.Value} {QuoteIdRaw(pAlias)}");
                    }

                    segmentIndex++;
                }
                else if (interpolation.Expression is IdentifierNameSyntax singleIdentifier &&
                         queryContext.Entities.TryGetValue(singleIdentifier.Identifier.Text, out var tableDecl))
                {
                    if (queryContext.SubqueryEntities.Contains(tableDecl.VariableName))
                    {
                        flushLiteral();
                        sb.AppendLine($"                    // AOT Mapped Subquery/Dynamic Fallback: {tableDecl.VariableName}");
                        sb.AppendLine($"                    genDb.AppendSegment(handler.GetSegment({segmentIndex}));");
                        segmentIndex++;
                        continue; 
                    }

                    string prevUpperText = "";
                    if (i > 0 && contents[i - 1] is InterpolatedStringTextSyntax prevTextSyntax)
                        prevUpperText = prevTextSyntax.TextToken.ValueText.ToUpperInvariant();
                        
                    bool isDeleteFrom = currentSqlClause == SqlKeyword.From.Value && prevUpperText.LastIndexOf(SqlKeyword.Delete.Value) > prevUpperText.LastIndexOf(SqlKeyword.Select.Value);

                    if (currentSqlClause == SqlKeyword.Insert.Value || currentSqlClause == SqlKeyword.Update.Value || isDeleteFrom)
                    {
                        flushLiteral();
                        sb.AppendLine($"                    // AOT Fallback to JIT for DML target entity context registration");
                        sb.AppendLine($"                    genDb.AppendSegment(handler.GetSegment({segmentIndex}));");
                        segmentIndex++;
                        continue;
                    }

                    if (analysis.InlineAliases.TryGetValue(tableDecl.VariableName, out var inlineAlias) && string.IsNullOrEmpty(format))
                    {
                        if (analysis.ReplacementForNextText.TryGetValue(i, out var rep))
                            activeTextReplacement = rep; 
                    }
                    
                    string wasAuto = tableDecl.WasAutoAliased.ToString().ToLower();

                    if (string.Equals(format, "columns", StringComparison.OrdinalIgnoreCase) ||
                              (string.IsNullOrEmpty(format) && (currentSqlClause == SqlKeyword.Select.Value || currentSqlClause == SqlKeyword.Returning.Value)))
                    {
                        flushLiteral();
                        sb.AppendLine($"                    // AOT Mapped Columns: {tableDecl.VariableName}");
                        
                        sb.AppendLine($"                    string indent_{segmentIndex} = new string(' ', indentSize);");
                        sb.AppendLine($"                    bool omitPrefix_{segmentIndex} = (\"{currentSqlClause}\" == \"{SqlKeyword.Insert.Value}\");");
                        
                        sb.AppendLine($"                    string prefix_{segmentIndex} = \"\";");
                        if (inlineAlias != null)
                        {
                            sb.AppendLine($"                    prefix_{segmentIndex} = {QuoteId(inlineAlias)} + \".\";");
                        }
                        else
                        {
                            sb.AppendLine($"                    bool suppressAutoAlias_{segmentIndex} = {analysis.IsDmlQuery.ToString().ToLower()} && {wasAuto};");
                            sb.AppendLine($"                    string resolvedAlias_{segmentIndex} = suppressAutoAlias_{segmentIndex} ? \"\" : genDb.ResolveAlias(\"{Escape(tableDecl.VariableName)}\", \"\", {wasAuto});");
                            sb.AppendLine($"                    if (!string.IsNullOrEmpty(resolvedAlias_{segmentIndex}))");
                            sb.AppendLine($"                    {{");
                            sb.AppendLine($"                        prefix_{segmentIndex} = {QuoteVar($"resolvedAlias_{segmentIndex}")} + \".\";");
                            sb.AppendLine($"                    }}");
                            sb.AppendLine($"                    else");
                            sb.AppendLine($"                    {{");
                            if (isRuntime) sb.AppendLine($"                        prefix_{segmentIndex} = {QuoteEnt(tableDecl.MappedTableName, tableDecl.MappedSchemaName)} + \".\";");
                            else sb.AppendLine($"                        prefix_{segmentIndex} = {QuoteEnt(tableDecl.MappedTableName, tableDecl.MappedSchemaName)} + \".\";");
                            sb.AppendLine($"                    }}");
                        }
                        
                        for (int k = 0; k < tableDecl.Columns.Count; k++)
                        {
                            var col = tableDecl.Columns[k];
                            if (k > 0)
                            {
                                sb.AppendLine($"                    if (layout == SqlCollectionLayout.Vertical)");
                                sb.AppendLine($"                    {{");
                                sb.AppendLine($"                        genDb.AppendRaw(\",\\n\");");
                                sb.AppendLine($"                        genDb.AppendRaw(indent_{segmentIndex});");
                                sb.AppendLine($"                    }}");
                                sb.AppendLine($"                    else genDb.AppendRaw(\", \");");
                            }
                            else
                            {
                                sb.AppendLine($"                    if (layout == SqlCollectionLayout.Vertical)");
                                sb.AppendLine($"                    {{");
                                sb.AppendLine($"                        genDb.AppendRaw(\"\\n\");");
                                sb.AppendLine($"                        genDb.AppendRaw(indent_{segmentIndex});");
                                sb.AppendLine($"                    }}");
                                
                                if (nextRequiresHorizontalSpace)
                                {
                                    sb.AppendLine($"                    else genDb.AppendRaw(\" \");");
                                }
                            }
                            
                            sb.AppendLine($"                    if (!omitPrefix_{segmentIndex}) genDb.AppendRaw(prefix_{segmentIndex});");
                            sb.AppendLine($"                    genDb.AppendRaw({QuoteId(col.ColumnName)});");
                        }
                        
                        nextRequiresHorizontalSpace = false;
                    }
                    else if (inlineAlias != null && string.IsNullOrEmpty(format))
                    {
                        flushLiteral();
                        sb.AppendLine($"                    // AOT Mapped Inline Alias Table: {tableDecl.VariableName} -> {inlineAlias}");
                        
                        sb.AppendLine($"                    var segVal_{segmentIndex} = handler.GetSegment({segmentIndex}).Value;");
                        sb.AppendLine($"                    if (segVal_{segmentIndex} is SqlInterpol.ISqlEntityBase entBase_{segmentIndex} && entBase_{segmentIndex}.Reference is SqlInterpol.ISqlAliasable aliasable_{segmentIndex})");
                        sb.AppendLine($"                    {{");
                        sb.AppendLine($"                        aliasable_{segmentIndex}.Alias = \"{Escape(inlineAlias)}\";");
                        sb.AppendLine($"                        aliasable_{segmentIndex}.IsAliasQuoted = false;");
                        sb.AppendLine($"                    }}");

                        sb.AppendLine($"                    genDb.AppendRaw(dialect.ApplyAlias({QuoteEnt(tableDecl.MappedTableName, tableDecl.MappedSchemaName)}, {QuoteId(inlineAlias)}));");
                    }
                    else if (isAliasHole)
                    {
                        sb.AppendLine($"                    // AOT Mapped Alias-Only: {tableDecl.VariableName}");
                        if (inlineAlias != null)
                        {
                            if (isRuntime) appendDynamic(QuoteId(inlineAlias));
                            else appendLiteral(QuoteIdRaw(inlineAlias));
                        }
                        else
                        {
                            flushLiteral();
                            sb.AppendLine($"                    string alias_{segmentIndex} = \"\";");
                            sb.AppendLine($"                    if (autoAliasing && {wasAuto}) alias_{segmentIndex} = \"{Escape(tableDecl.VariableName)}\";");

                            sb.AppendLine($"                    var segVal_{segmentIndex} = handler.GetSegment({segmentIndex}).Value;");
                            sb.AppendLine($"                    if (segVal_{segmentIndex} is SqlInterpol.ISqlEntityBase entBase_{segmentIndex})");
                            sb.AppendLine($"                    {{");
                            sb.AppendLine($"                        if (!string.IsNullOrEmpty(entBase_{segmentIndex}.Reference.Alias)) alias_{segmentIndex} = entBase_{segmentIndex}.Reference.Alias;");
                            sb.AppendLine($"                        else if (string.IsNullOrEmpty(alias_{segmentIndex})) alias_{segmentIndex} = entBase_{segmentIndex}.Reference.FallbackAlias ?? \"{Escape(tableDecl.MappedTableName)}\";");
                            sb.AppendLine($"                    }}");

                            if (isRuntime) sb.AppendLine($"                    genDb.AppendRaw({QuoteVar($"alias_{segmentIndex}")});");
                            else sb.AppendLine($"                    genDb.AppendRaw(\"{Escape(quotes.Open)}\" + alias_{segmentIndex} + \"{Escape(quotes.Close)}\");");
                        }
                    }
                    else if (string.Equals(format, "base", StringComparison.OrdinalIgnoreCase))
                    {
                        sb.AppendLine($"                    // AOT Mapped Base-Only: {tableDecl.VariableName}");
                        if (isRuntime) appendDynamic(QuoteEnt(tableDecl.MappedTableName, tableDecl.MappedSchemaName));
                        else appendLiteral(QuoteEntRaw(tableDecl.MappedTableName, tableDecl.MappedSchemaName));
                    }
                    else
                    {
                        flushLiteral();
                        sb.AppendLine($"                    // AOT Mapped Table: {tableDecl.VariableName} -> {tableDecl.MappedTableName}");
                        
                        sb.AppendLine($"                    bool suppressAutoAlias_{segmentIndex} = {analysis.IsDmlQuery.ToString().ToLower()} && {wasAuto};");
                        sb.AppendLine($"                    string alias_{segmentIndex} = \"\";");
                        sb.AppendLine($"                    if (!suppressAutoAlias_{segmentIndex}) alias_{segmentIndex} = genDb.ResolveAlias(\"{Escape(tableDecl.VariableName)}\", \"\", {wasAuto});");
                        
                        sb.AppendLine($"                    var segVal_{segmentIndex} = handler.GetSegment({segmentIndex}).Value;");
                        sb.AppendLine($"                    if (segVal_{segmentIndex} is SqlInterpol.ISqlEntityBase entBase_{segmentIndex} && entBase_{segmentIndex}.Reference is SqlInterpol.ISqlAliasable aliasable_{segmentIndex})");
                        sb.AppendLine($"                    {{");
                        sb.AppendLine($"                        aliasable_{segmentIndex}.Alias = alias_{segmentIndex};");
                        sb.AppendLine($"                        aliasable_{segmentIndex}.IsAliasQuoted = false;");
                        sb.AppendLine($"                    }}");

                        sb.AppendLine($"                    string quotedAlias_{segmentIndex} = string.IsNullOrEmpty(alias_{segmentIndex}) ? \"\" : {QuoteVar($"alias_{segmentIndex}")};");
                        sb.AppendLine($"                    genDb.AppendRaw(dialect.ApplyAlias({QuoteEnt(tableDecl.MappedTableName, tableDecl.MappedSchemaName)}, quotedAlias_{segmentIndex}));");
                    }

                    segmentIndex++;
                }
                else
                {
                    flushLiteral();
                    sb.AppendLine($"                    genDb.AppendSegment(handler.GetSegment({segmentIndex}));");
                    segmentIndex++;
                }
            }
        }
        
        flushLiteral();
        
        sb.AppendLine("                    break;");
        sb.AppendLine("                }");
    }
}