using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

#pragma warning disable RSEXPERIMENTAL002
namespace SqlInterpol.Generators;

public partial class SqlAotInterceptorGenerator
{
    private static void Emit(SourceProductionContext spc, ImmutableArray<CompileTimeQueryContext> contexts, ImmutableArray<string> dialects, Compilation compilation)
    {
        var processedInvocations = new HashSet<SyntaxNode>();
        int uniqueAppendsFound = 0;
        int uniqueEntitiesFound = 0;

        var dialectQuotes = ExtractDialectQuotes(dialects, compilation);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8019");
        sb.AppendLine("#pragma warning disable CS9251");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SqlInterpol;");
        
        sb.AppendLine("using SqlInterpol.Configuration;");
        sb.AppendLine("using SqlInterpol.Execution;");
        sb.AppendLine("using SqlInterpol.Infrastructure;");
        sb.AppendLine("using SqlInterpol.Schema;");
        sb.AppendLine("using SqlInterpol.Segments;");
        sb.AppendLine("");
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) {}");
        sb.AppendLine("        public InterceptsLocationAttribute(string filePath, int line, int character) {}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("");
        sb.AppendLine("namespace SqlInterpol.Generators.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class AotInterceptors");
        sb.AppendLine("    {");

        int interceptorCount = 0;

        foreach (var queryContext in contexts)
        {
            if (queryContext == null) continue;

            foreach (var appendCall in queryContext.AppendCalls)
            {
                if (!processedInvocations.Add(appendCall.InvocationNode))
                    continue;

                uniqueAppendsFound++;

                var syntaxTree = appendCall.InvocationNode.SyntaxTree;
                var semanticModel = compilation.GetSemanticModel(syntaxTree);

                string interceptorMethodName = $"Intercepted_{appendCall.MethodName}_{interceptorCount++}";

                var interceptableLocation = semanticModel.GetInterceptableLocation(appendCall.InvocationNode);
                if (interceptableLocation != null)
                {
                    var attrSyntax = interceptableLocation.GetInterceptsLocationAttributeSyntax();
                    sb.AppendLine($"        {attrSyntax}");
                }
                else
                {
                    var filePath = syntaxTree.FilePath;
                    var memberAccess = (MemberAccessExpressionSyntax)appendCall.InvocationNode.Expression;
                    var lineSpan = syntaxTree.GetLineSpan(memberAccess.Name.Span);
                    var line = lineSpan.StartLinePosition.Line + 1;
                    var character = lineSpan.StartLinePosition.Character + 1;
                    var normalizedPath = filePath.Replace("\\", "\\\\");
                    sb.AppendLine($"        [InterceptsLocation(@\"{normalizedPath}\", {line}, {character})]");
                }

                sb.AppendLine($"        public static SqlBuilder {interceptorMethodName}(this SqlBuilder builder, ref {appendCall.HandlerTypeDisplayString} handler)");
                sb.AppendLine("        {");
                sb.AppendLine("            var genDb = (ISqlGeneratorBuilder)builder;");

                var arguments = appendCall.InvocationNode.ArgumentList.Arguments;
                if (arguments.Count == 0)
                {
                    if (appendCall.MethodName == "AppendLine")
                        sb.AppendLine("            genDb.AppendSegment(new SqlInterpol.Segments.SqlSegment(SqlInterpol.Segments.SqlSegmentType.Literal, \"\\n\"));");
                    
                    sb.AppendLine("            return builder;");
                    sb.AppendLine("        }");
                    continue;
                }

                var firstArg = arguments[0].Expression;
                if (firstArg is InterpolatedStringExpressionSyntax interpolatedString)
                {
                    var analysis = AnalyzeContents(interpolatedString, queryContext);
                    
                    if (analysis.RequiresJitFallback)
                    {
                        // Emit Roslyn Diagnostic so the developer knows the query is falling back to JIT
                        string reason = analysis switch
                        {
                            { HasWindowFunction: true } => "a window function (OVER)",
                            { HasSetOperation: true } => "a set operation (UNION/INTERSECT/EXCEPT)",
                            { HasUpsert: true } => "an UPSERT/MERGE operation",
                            { HasComplexDynamicHoles: true } => "a dynamically evaluated SQL fragment",
                            { HasReturning: true } => "a RETURNING clause",
                            _ => "unsupported dynamic parameters or complex aliases"
                        };

                        spc.ReportDiagnostic(Diagnostic.Create(
                            SqlAotDiagnostics.JitFallbackDiagnostic,
                            interpolatedString.GetLocation(),
                            reason));

                        sb.AppendLine("            builder.Append(ref handler); // JIT Dynamic Fallback");
                        
                        if (appendCall.MethodName == "AppendLine")
                            sb.AppendLine("            genDb.AppendSegment(new SqlInterpol.Segments.SqlSegment(SqlInterpol.Segments.SqlSegmentType.Literal, \"\\n\"));");
                        
                        sb.AppendLine("            return builder;");
                        sb.AppendLine("        }");
                        sb.AppendLine("");
                        continue;
                    }

                    sb.AppendLine("            genDb.IsAotIntercepted = true;");
                    sb.AppendLine("            var ctx = genDb.Context;");
                    
                    // FIX: Unbox the strictly non-nullable options!
                    sb.AppendLine("            var options = ctx.Options.Value;");
                    
                    sb.AppendLine("            var dialect = ctx.Dialect;");
                    sb.AppendLine("            string dialectKind = dialect.Kind.Value;");
                    sb.AppendLine("            var layout = options.CollectionLayout;");
                    sb.AppendLine("            int indentSize = options.IndentSize;");
                    sb.AppendLine("            bool autoAliasing = options.EntityAutoAliasing;");
                    sb.AppendLine();
                    sb.AppendLine($"            switch (dialectKind)");
                    sb.AppendLine("            {");
                    
                    var targetDialects = dialects.ToList();
                    targetDialects.Add("RUNTIME");
                    
                    foreach (var targetDialect in targetDialects)
                    {
                        var quotes = dialectQuotes.TryGetValue(targetDialect, out var q) ? q : ("\"", "\"");
                        EmitDialectSwitchCase(sb, targetDialect, interpolatedString, queryContext, analysis, quotes);
                    }
                    
                    sb.AppendLine("            }");
                }
                else if (firstArg is LiteralExpressionSyntax literal)
                {
                    var text = literal.Token.ValueText.Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");
                    sb.AppendLine($"            genDb.AppendSegment(new SqlInterpol.Segments.SqlSegment(SqlInterpol.Segments.SqlSegmentType.Literal, \"{text}\"));");
                }
                else
                {
                    sb.AppendLine("            builder.Append(ref handler); // JIT Dynamic Fallback");
                }

                if (appendCall.MethodName == "AppendLine")
                {
                    sb.AppendLine("            genDb.AppendSegment(new SqlInterpol.Segments.SqlSegment(SqlInterpol.Segments.SqlSegmentType.Literal, \"\\n\"));");
                }

                sb.AppendLine("            return builder;");
                sb.AppendLine("        }");
                sb.AppendLine("");
            }
            
            uniqueEntitiesFound += queryContext.Entities.Count;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("AotDiagnostics.g.cs", $@"// <auto-generated/>
// Active AOT Target Dialects: {string.Join(", ", dialects)}
// Found {uniqueEntitiesFound} tracked db.Entity() declarations.
// Found {uniqueAppendsFound} unique Append/AppendLine calls to intercept.");
        
        spc.AddSource("AotInterceptors.g.cs", sb.ToString());
    }
}

