using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SqlInterpol.Generators;

[Generator]
public class SqlAotInterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitContext =>
        {
            postInitContext.AddSource("InterceptsLocationAttribute.g.cs", @"// <auto-generated/>
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) {}
        public InterceptsLocationAttribute(string filePath, int line, int character) {}
    }
}");
        });

        var dialectsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                if (options.GlobalOptions.TryGetValue("build_property.sqlinterpoldialects", out var dialectsString) 
                    && !string.IsNullOrWhiteSpace(dialectsString))
                {
                    return dialectsString.Split(',', ';').Select(d => d.Trim()).Where(d => !string.IsNullOrEmpty(d)).ToImmutableArray();
                }
                return ImmutableArray.Create("PostgreSql");
            });

        var queryContextProvider = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
            {
                if (node is not InvocationExpressionSyntax invocation) return false;
                if (invocation.Expression is MemberAccessExpressionSyntax memberAccess)
                {
                    var name = memberAccess.Name.Identifier.Text;
                    return name is "Append" or "AppendLine";
                }
                return false;
            },
            transform: static (ctx, _) =>
            {
                var containingMethod = ctx.Node.Ancestors().OfType<MethodDeclarationSyntax>().FirstOrDefault();
                if (containingMethod == null) return null;
                var walker = new SqlAotSyntaxWalker(ctx.SemanticModel);
                walker.Visit(containingMethod);
                return walker.CurrentContext.AppendCalls.Count > 0 ? walker.CurrentContext : null;
            })
            .Where(static ctx => ctx != null);

        var compilationProvider = queryContextProvider.Collect().Combine(dialectsProvider);

        context.RegisterSourceOutput(compilationProvider, static (spc, source) =>
        {
            var (contexts, dialects) = source;
            if (contexts.IsEmpty) return;

            var processedInvocations = new HashSet<SyntaxNode>();
            int uniqueAppendsFound = 0;
            int uniqueEntitiesFound = 0;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS8019");
            sb.AppendLine("#pragma warning disable CS9251");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using SqlInterpol;");
            sb.AppendLine("");
            sb.AppendLine("namespace SqlInterpol.Generators.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class AotInterceptors");
            sb.AppendLine("    {");

            int interceptorCount = 0;

            foreach (var queryContext in contexts)
            {
                if (queryContext == null) continue;

                foreach (var appendCall in queryContext.AppendCalls)
                {
                    if (!processedInvocations.Add(appendCall.InvocationNode))
                        continue;

                    uniqueAppendsFound++;

                    var syntaxTree = appendCall.InvocationNode.SyntaxTree;
                    var filePath = syntaxTree.FilePath;
                    
                    var memberAccess = (MemberAccessExpressionSyntax)appendCall.InvocationNode.Expression;
                    var lineSpan = syntaxTree.GetLineSpan(memberAccess.Name.Span);
                    var line = lineSpan.StartLinePosition.Line + 1;
                    var character = lineSpan.StartLinePosition.Character + 1;

                    string interceptorMethodName = $"Intercepted_{appendCall.MethodName}_{interceptorCount++}";
                    var normalizedPath = filePath.Replace("\\", "\\\\");

                    sb.AppendLine($"        [InterceptsLocation(@\"{normalizedPath}\", {line}, {character})]");
                    sb.AppendLine($"        public static SqlBuilder {interceptorMethodName}(this SqlBuilder builder, ref {appendCall.HandlerTypeDisplayString} handler)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var genDb = (ISqlGeneratorBuilder)builder;");

                    var arguments = appendCall.InvocationNode.ArgumentList.Arguments;
                    if (arguments.Count == 0)
                    {
                        sb.AppendLine("            return builder;");
                        sb.AppendLine("        }");
                        continue;
                    }

                    var firstArg = arguments[0].Expression;

                    if (firstArg is InterpolatedStringExpressionSyntax interpolatedString)
                    {
                        int segmentIndex = 0;
                        string currentSqlClause = "UNKNOWN";

                        // =========================================================
                        // PRE-PASS: Safely parse inline aliases and parenthesis
                        // =========================================================
                        var inlineAliases = new Dictionary<string, string>();
                        var replacementForNextText = new Dictionary<int, string>();
                        var contents = interpolatedString.Contents;

                        for (int i = 0; i < contents.Count; i++)
                        {
                            if (contents[i] is InterpolationSyntax interpolation &&
                                interpolation.Expression is IdentifierNameSyntax ident &&
                                queryContext.Entities.ContainsKey(ident.Identifier.Text))
                            {
                                string? format = interpolation.FormatClause?.FormatStringToken.ValueText;
                                if (string.IsNullOrEmpty(format))
                                {
                                    if (i + 1 < contents.Count && contents[i + 1] is InterpolatedStringTextSyntax nextText)
                                    {
                                        var rawText = nextText.TextToken.ValueText;
                                        
                                        string rawTrimmed = rawText.TrimStart(' ', '\r', '\n', '\t', ')', ']');
                                        if (rawTrimmed.StartsWith("AS ", StringComparison.OrdinalIgnoreCase))
                                        {
                                            var parts = rawTrimmed.Substring(3).TrimStart().Split(new[] { ' ', '\r', '\n', '\t', ',', ')' }, StringSplitOptions.RemoveEmptyEntries);
                                            if (parts.Length > 0)
                                            {
                                                string cleanAlias = parts[0].Trim('[', ']', '"', '\'', '`');
                                                inlineAliases[ident.Identifier.Text] = cleanAlias;
                                                
                                                // 🌟 CRITICAL FIX: Consume ONLY spaces and tabs immediately before AS to prevent trailing space bugs!
                                                var regex = new System.Text.RegularExpressions.Regex(@"[ \t]*\bAS\s+\[?" + System.Text.RegularExpressions.Regex.Escape(cleanAlias) + @"\]?\b", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
                                                replacementForNextText[i] = regex.Replace(rawText, "", 1);
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        // =========================================================
                        // AOT EMISSION PASS
                        // =========================================================
                        string activeTextReplacement = null;

                        for (int i = 0; i < contents.Count; i++)
                        {
                            var content = contents[i];

                            if (content is InterpolatedStringTextSyntax textContent)
                            {
                                var rawText = textContent.TextToken.ValueText;
                                
                                if (activeTextReplacement != null)
                                {
                                    rawText = activeTextReplacement;
                                    activeTextReplacement = null;
                                }

                                var upperText = rawText.ToUpperInvariant();
                                int selIdx = upperText.LastIndexOf("SELECT");
                                int fromIdx = upperText.LastIndexOf("FROM");
                                int joinIdx = upperText.LastIndexOf("JOIN");
                                int updateIdx = upperText.LastIndexOf("UPDATE");
                                int setIdx = upperText.LastIndexOf("SET");
                                int retIdx = upperText.LastIndexOf("RETURNING");

                                int maxIdx = Math.Max(selIdx, Math.Max(fromIdx, Math.Max(joinIdx, Math.Max(updateIdx, Math.Max(setIdx, retIdx)))));
                                if (maxIdx != -1)
                                {
                                    if (maxIdx == selIdx) currentSqlClause = "SELECT";
                                    else if (maxIdx == fromIdx) currentSqlClause = "FROM";
                                    else if (maxIdx == joinIdx) currentSqlClause = "JOIN";
                                    else if (maxIdx == updateIdx) currentSqlClause = "UPDATE";
                                    else if (maxIdx == setIdx) currentSqlClause = "SET";
                                    else if (maxIdx == retIdx) currentSqlClause = "RETURNING";
                                }

                                var text = rawText.Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n"); 
                                sb.AppendLine($"            genDb.AppendRaw(\"{text}\");");
                            }
                            else if (content is InterpolationSyntax interpolation)
                            {
                                string? format = interpolation.FormatClause?.FormatStringToken.ValueText;

                                if (interpolation.Expression is MemberAccessExpressionSyntax holeMemberAccess &&
                                    holeMemberAccess.Expression is IdentifierNameSyntax identifier &&
                                    queryContext.Entities.TryGetValue(identifier.Identifier.Text, out var entityDecl))
                                {
                                    var propertyName = holeMemberAccess.Name.Identifier.Text;
                                    var colMap = entityDecl.Columns.FirstOrDefault(c => c.PropertyName == propertyName);
                                    var columnName = colMap != null ? colMap.ColumnName : propertyName;
                                        
                                    string wasAuto = entityDecl.WasAutoAliased.ToString().ToLower();

                                    if (string.Equals(format, "alias", StringComparison.OrdinalIgnoreCase))
                                    {
                                        sb.AppendLine($"            // AOT Mapped Property Alias: {columnName}");
                                        sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(\"{columnName}\"));");
                                    }
                                    else
                                    {
                                        sb.AppendLine($"            // AOT Mapped Property: {identifier.Identifier.Text}.{propertyName} -> {columnName}");
                                        if (inlineAliases.TryGetValue(entityDecl.VariableName, out var inlineAlias))
                                            sb.AppendLine($"            string alias_{segmentIndex} = \"{inlineAlias}\";");
                                        else
                                            sb.AppendLine($"            string alias_{segmentIndex} = genDb.ResolveAlias(\"{entityDecl.VariableName}\", \"{entityDecl.TypeName}\", {wasAuto});");

                                        sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(alias_{segmentIndex}));");
                                        sb.AppendLine($"            genDb.AppendRaw(\".\");");
                                        sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(\"{columnName}\"));");
                                    }
                                    segmentIndex++;
                                }
                                else if (interpolation.Expression is IdentifierNameSyntax singleIdentifier &&
                                         queryContext.Entities.TryGetValue(singleIdentifier.Identifier.Text, out var tableDecl))
                                {
                                    // ============================================================
                                    // 🌟 CRITICAL FIX: Ensure Subqueries fallback immediately to JIT
                                    // PRESERVING the ") AS alias" string format for the next loop!
                                    // ============================================================
                                    if (queryContext.SubqueryEntities.Contains(tableDecl.VariableName))
                                    {
                                        sb.AppendLine($"            // AOT Mapped Subquery Fallback: {tableDecl.VariableName}");
                                        sb.AppendLine($"            genDb.AppendSegment(handler.GetSegment({segmentIndex}));");
                                        segmentIndex++;
                                        continue; 
                                    }

                                    // Safely trigger alias text replacements ONLY for standard tables!
                                    if (inlineAliases.TryGetValue(tableDecl.VariableName, out var inlineAlias) && string.IsNullOrEmpty(format))
                                    {
                                        if (replacementForNextText.TryGetValue(i, out var rep))
                                            activeTextReplacement = rep; 
                                    }

                                    string wasAuto = tableDecl.WasAutoAliased.ToString().ToLower();

                                    if (string.Equals(format, "columns", StringComparison.OrdinalIgnoreCase) || 
                                             (string.IsNullOrEmpty(format) && (currentSqlClause == "SELECT" || currentSqlClause == "RETURNING")))
                                    {
                                        sb.AppendLine($"            // AOT Mapped Columns: {tableDecl.VariableName}");
                                        if (inlineAlias != null)
                                            sb.AppendLine($"            string alias_{segmentIndex} = \"{inlineAlias}\";");
                                        else
                                            sb.AppendLine($"            string alias_{segmentIndex} = genDb.ResolveAlias(\"{tableDecl.VariableName}\", \"{tableDecl.TypeName}\", {wasAuto});");
                                        
                                        for (int k = 0; k < tableDecl.Columns.Count; k++)
                                        {
                                            var col = tableDecl.Columns[k];
                                            if (k > 0) sb.AppendLine($"            genDb.AppendRaw(\", \");");
                                            sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(alias_{segmentIndex}));");
                                            sb.AppendLine($"            genDb.AppendRaw(\".\");");
                                            sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(\"{col.ColumnName}\"));");
                                        }
                                    }
                                    else if (inlineAlias != null && string.IsNullOrEmpty(format))
                                    {
                                        sb.AppendLine($"            // AOT Mapped Inline Alias Table: {tableDecl.VariableName} -> {inlineAlias}");
                                        sb.AppendLine($"            string baseTbl_{segmentIndex} = \"\";");
                                        if (tableDecl.MappedSchemaName != null)
                                            sb.AppendLine($"            baseTbl_{segmentIndex} += genDb.Context.Dialect.QuoteIdentifier(\"{tableDecl.MappedSchemaName}\") + \".\";");
                                        sb.AppendLine($"            baseTbl_{segmentIndex} += genDb.Context.Dialect.QuoteIdentifier(\"{tableDecl.MappedTableName}\");");
                                        
                                        sb.AppendLine($"            string qAlias_{segmentIndex} = genDb.Context.Dialect.QuoteIdentifier(\"{inlineAlias}\");");
                                        sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.ApplyAlias(baseTbl_{segmentIndex}, qAlias_{segmentIndex}));");
                                    }
                                    else if (string.Equals(format, "alias", StringComparison.OrdinalIgnoreCase))
                                    {
                                        sb.AppendLine($"            // AOT Mapped Alias-Only: {tableDecl.VariableName}");
                                        if (inlineAlias != null)
                                            sb.AppendLine($"            string alias_{segmentIndex} = \"{inlineAlias}\";");
                                        else
                                            sb.AppendLine($"            string alias_{segmentIndex} = genDb.ResolveAlias(\"{tableDecl.VariableName}\", \"{tableDecl.TypeName}\", {wasAuto});");
                                        
                                        sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(alias_{segmentIndex}));");
                                    }
                                    else if (string.Equals(format, "base", StringComparison.OrdinalIgnoreCase))
                                    {
                                        sb.AppendLine($"            // AOT Mapped Base-Only: {tableDecl.VariableName}");
                                        if (tableDecl.MappedSchemaName != null)
                                        {
                                            sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(\"{tableDecl.MappedSchemaName}\"));");
                                            sb.AppendLine($"            genDb.AppendRaw(\".\");");
                                        }
                                        sb.AppendLine($"            genDb.AppendRaw(genDb.Context.Dialect.QuoteIdentifier(\"{tableDecl.MappedTableName}\"));");
                                    }
                                    else
                                    {
                                        sb.AppendLine($"            // AOT Mapped Table: {tableDecl.VariableName} -> {tableDecl.MappedTableName}");
                                        sb.AppendLine($"            string baseTbl_{segmentIndex} = \"\";");
                                        if (tableDecl.MappedSchemaName != null)
                                            sb.AppendLine($"            baseTbl_{segmentIndex} += genDb.Context.Dialect.QuoteIdentifier(\"{tableDecl.MappedSchemaName}\") + \".\";");
                                        sb.AppendLine($"            baseTbl_{segmentIndex} += genDb.Context.Dialect.QuoteIdentifier(\"{tableDecl.MappedTableName}\");");

                                        sb.AppendLine($"            if (!{wasAuto} || genDb.Context.Options.EntityAutoAliasing)");
                                        sb.AppendLine($"            {{");
                                        sb.AppendLine($"                string alias_{segmentIndex} = genDb.ResolveAlias(\"{tableDecl.VariableName}\", \"{tableDecl.TypeName}\", {wasAuto});");
                                        sb.AppendLine($"                string qAlias_{segmentIndex} = genDb.Context.Dialect.QuoteIdentifier(alias_{segmentIndex});");
                                        sb.AppendLine($"                genDb.AppendRaw(genDb.Context.Dialect.ApplyAlias(baseTbl_{segmentIndex}, qAlias_{segmentIndex}));");
                                        sb.AppendLine($"            }}");
                                        sb.AppendLine($"            else");
                                        sb.AppendLine($"            {{");
                                        sb.AppendLine($"                genDb.AppendRaw(baseTbl_{segmentIndex});");
                                        sb.AppendLine($"            }}");
                                    }
                                    segmentIndex++;
                                }
                                else
                                {
                                    sb.AppendLine($"            genDb.AppendSegment(handler.GetSegment({segmentIndex}));");
                                    segmentIndex++;
                                }
                            }
                        }
                    }
                    else if (firstArg is LiteralExpressionSyntax literal)
                    {
                        var text = literal.Token.ValueText.Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");
                        sb.AppendLine($"            genDb.AppendRaw(\"{text}\");");
                    }
                    else
                    {
                        sb.AppendLine("            builder.Append(ref handler); // JIT Dynamic Fallback");
                    }

                    if (appendCall.MethodName == "AppendLine")
                    {
                        sb.AppendLine("            genDb.AppendRaw(\"\\n\");");
                    }

                    sb.AppendLine("            return builder;");
                    sb.AppendLine("        }");
                    sb.AppendLine("");
                }

                uniqueEntitiesFound += queryContext.Entities.Count;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("AotDiagnostics.g.cs", $@"
// <auto-generated/>
// Active AOT Target Dialects: {string.Join(", ", dialects)}
// Found {uniqueEntitiesFound} tracked db.Entity() declarations.
// Found {uniqueAppendsFound} unique Append/AppendLine calls to intercept.
");
            spc.AddSource("AotInterceptors.g.cs", sb.ToString());
        });
    }
}