using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SqlInterpol.Generators;

[Generator]
public class SqlFragmentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "SqlInterpol.SqlFragmentAttribute",
                predicate: static (s, _) => s is MethodDeclarationSyntax,
                transform: static (ctx, _) => ctx.TargetSymbol as IMethodSymbol)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(methodDeclarations, static (spc, methodSymbol) =>
        {
            GenerateWrapperMethod(spc, methodSymbol!);
        });
    }

    private static void GenerateWrapperMethod(SourceProductionContext spc, IMethodSymbol method)
    {
        var containingClass = method.ContainingType;

        // --- DIAGNOSTIC CHECK 1: Ensure the class is static ---
        if (!containingClass.IsStatic)
        {
            var diagnostic = Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "SQLGEN001",
                    title: "Invalid SqlFragment Container",
                    messageFormat: "The class '{0}' must be static to contain a [SqlFragment] method",
                    category: "Usage",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                method.Locations.FirstOrDefault(),
                containingClass.Name);

            spc.ReportDiagnostic(diagnostic);
            return; 
        }

        // --- DIAGNOSTIC CHECK 2: Prevent Extension Method Shadowing ---
        if (method.IsExtensionMethod)
        {
            var diagnostic = Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "SQLGEN002",
                    title: "Invalid SqlFragment Signature",
                    messageFormat: "The method '{0}' cannot be an extension method. Remove the 'this' modifier from the first parameter. The source generator will automatically emit the 'this' modifier on the generated public wrapper.",
                    category: "Usage",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                method.Locations.FirstOrDefault(),
                method.Name);

            spc.ReportDiagnostic(diagnostic);
            return; 
        }

        var namespaceName = containingClass.ContainingNamespace.ToDisplayString();
        var className = containingClass.Name;
        var methodName = method.Name;
        var returnType = method.ReturnType.ToDisplayString();

        string classAccessibility = containingClass.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => "internal"
        };

        var builderParam = method.Parameters[0];
        var otherParams = method.Parameters.Skip(1).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SqlInterpol;");
        sb.AppendLine("");
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine("");
        sb.AppendLine($"{classAccessibility} static partial class {className}");
        sb.AppendLine("{");

        // 1. Core Signature (Automatically upgrades the target to an extension method!)
        sb.Append($"    public static {returnType} {methodName}(this {builderParam.Type.ToDisplayString()} {builderParam.Name}");
        
        // 2. Add Parameters (Entities get 'Ref', Scalars keep their original name)
        foreach (var p in otherParams)
        {
            if (IsEntityParameter(p.Type))
                sb.Append($", {p.Type.ToDisplayString()} {p.Name}Ref");
            else
                sb.Append($", {p.Type.ToDisplayString()} {p.Name}");
        }

        // 3. Add CallerArgumentExpressions (ONLY for Entities)
        foreach (var p in otherParams)
        {
            if (IsEntityParameter(p.Type))
                sb.Append($", [CallerArgumentExpression(nameof({p.Name}Ref))] string? {p.Name}Key = null");
        }
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // 4. Generate the DB Bindings (ONLY for Entities)
        foreach (var p in otherParams)
        {
            if (IsEntityParameter(p.Type))
            {
                sb.AppendLine($"        {builderParam.Name}.Entity<{p.Type.ToDisplayString()}>({p.Name}Key, out var {p.Name});");
            }
        }

        // 5. Call the user's private method with the correct variable names!
        sb.Append($"        return {methodName}({builderParam.Name}");
        foreach (var p in otherParams)
        {
            sb.Append($", {p.Name}");
        }
        sb.AppendLine(");");
        
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{className}.{methodName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Heuristic to determine if a type is a database entity or a scalar pass-through parameter.
    /// </summary>
    private static bool IsEntityParameter(ITypeSymbol type)
    {
        if (type.SpecialType != SpecialType.None) return false;

        string name = type.Name;
        if (name is "Guid" or "DateTime" or "DateTimeOffset" or "TimeSpan" or "Decimal" or "String") 
            return false;

        return true;
    }
}