using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Collections.Immutable;

namespace SqlInterpol.Testing.Generators;

[Generator]
public class SqlTestSuiteGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Find classes with a base list (e.g. implementing interfaces)
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.BaseList != null && c.BaseList.Types.Count > 0,
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var templateFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".cs"))
            .Select(static (file, ct) => file.GetText(ct)?.ToString())
            .Where(static text => text != null)
            .Collect();

        var combined = classDeclarations.Combine(templateFiles);
        context.RegisterSourceOutput(combined, static (spc, source) => Execute(spc, source.Left!.Value, source.Right));
    }

    private static (ClassDeclarationSyntax Syntax, INamedTypeSymbol Symbol, INamedTypeSymbol TemplateSymbol)? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
        if (symbol == null) return null;

        // Find if any implemented interface has [SqlTestSuite(typeof(Template))]
        foreach (var iface in symbol.AllInterfaces)
        {
            var suiteAttr = iface.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "SqlTestSuiteAttribute");
            if (suiteAttr != null)
            {
                var templateSymbol = suiteAttr.ConstructorArguments.FirstOrDefault().Value as INamedTypeSymbol;
                if (templateSymbol != null)
                {
                    return (classSyntax, symbol, templateSymbol);
                }
            }
        }

        return null;
    }

    private static void Execute(
        SourceProductionContext context, 
        (ClassDeclarationSyntax Syntax, INamedTypeSymbol ClassSymbol, INamedTypeSymbol TemplateSymbol) target, 
        ImmutableArray<string?> templates)
    {
        var className = target.ClassSymbol.Name;
        var namespaceName = target.ClassSymbol.ContainingNamespace.ToDisplayString();
        var rawFilePath = target.ClassSymbol.Locations.FirstOrDefault()?.SourceTree?.FilePath;
        var normalizedPath = rawFilePath?.Replace('\\', '/');
        var templateName = target.TemplateSymbol.Name;

        // Find and parse the matching template file
        ClassDeclarationSyntax? templateClass = null;
        foreach (var templateStr in templates)
        {
            if (templateStr != null && templateStr.Contains(templateName))
            {
                var tree = CSharpSyntaxTree.ParseText(templateStr);
                templateClass = tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>()
                    .FirstOrDefault(c => c.Identifier.Text == templateName);
                if (templateClass != null) break;
            }
        }

        if (templateClass == null) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        // Collect standard and template usings, then deduplicate
        var usingsList = new List<string>
        {
            "using SqlInterpol.Schema;",
            "using SqlInterpol.Testing.Xunit;",
            "using Xunit;"
        };

        var templateRoot = templateClass.SyntaxTree.GetRoot() as CompilationUnitSyntax;
        if (templateRoot != null)
        {
            foreach (var u in templateRoot.Usings)
            {
                usingsList.Add(u.ToFullString().Trim());
            }
        }

        foreach (var u in usingsList.Distinct())
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        
        // Use partial class to merge with the user's handwritten test data
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        // Iterate through all members of the template
        foreach (var member in templateClass.Members)
        {
            // Check for [SqlIgnoreMember] and skip copying it
            var hasIgnoreAttr = member.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(a => a.Name.ToString() == "SqlIgnoreMember" || a.Name.ToString() == "SqlIgnoreMemberAttribute");

            if (hasIgnoreAttr)
            {
                continue;
            }

            if (member is MethodDeclarationSyntax method)
            {
                // Check if it has [SqlTest("DataPropertyName")]
                var sqlTestAttr = method.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .FirstOrDefault(a => a.Name.ToString() == "SqlTest" || a.Name.ToString() == "SqlTestAttribute");

                if (sqlTestAttr != null)
                {
                    var dataPropertyName = sqlTestAttr.ArgumentList?.Arguments.FirstOrDefault()?.ToString().Trim('"');
                    
                    // Look up line number in the handwritten user file
                    int lineNumber = 1;
                    if (!string.IsNullOrEmpty(dataPropertyName))
                    {
                        var dataMember = target.ClassSymbol.GetMembers(dataPropertyName!).FirstOrDefault();
                        if (dataMember != null)
                        {
                            var location = dataMember.Locations.FirstOrDefault();
                            if (location != null) lineNumber = location.GetLineSpan().StartLinePosition.Line + 1;
                        }
                    }

                    // Write the Ctrl+Click link
                    if (normalizedPath != null)
                    {
                        sb.AppendLine($"    // Ctrl+Click to edit test data: file:///{normalizedPath}#{lineNumber}");
                    }
                    
                    // Replace [SqlTest] with xUnit [Theory] and [MemberData]
                    sb.AppendLine("    [Theory]");
                    sb.AppendLine($"    [MemberData(nameof({dataPropertyName}))]");
                    
                    // Safely grab modifiers (like async) and ensure the method is public
                    var modifiers = method.Modifiers.ToFullString().Trim();
                    if (!modifiers.Contains("public"))
                    {
                        modifiers = "public " + modifiers;
                    }
                    
                    // Write the rest of the method signature and body EXACTLY as it is in the template
                    sb.AppendLine($"    {modifiers.Trim()} {method.ReturnType} {method.Identifier}{method.ParameterList}");
                    sb.AppendLine(method.Body?.ToFullString() ?? $"    {{ {method.ExpressionBody?.ToFullString()}; }}");
                    sb.AppendLine();
                    continue;
                }
            }

            // If it's a field, helper method, or anything else, just paste it verbatim!
            sb.AppendLine("    " + member.ToFullString().Trim());
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}