using Xunit;
using Xunit.Sdk;

namespace SqlInterpol.Testing.Xunit;

/// <summary>
/// Provides assertion methods specifically designed for validating SQL generation and parameterization.
/// </summary>
public static class SqlAssert
{
    /// <summary>
    /// Verifies that two SQL strings are equivalent, ignoring platform-specific line endings (normalizes \r\n to \n).
    /// </summary>
    /// <param name="expected">The expected SQL string.</param>
    /// <param name="actual">The actual SQL string generated by the builder.</param>
    /// <exception cref="EqualException">Thrown when the normalized strings do not match.</exception>
    public static void MatchesSql(string expected, string actual)
    {
        const string WindowsLineEnding = "\r\n";
        const string UnixLineEnding = "\n";

        // Only normalize Windows (\r\n) and classic Mac (\r) to Linux (\n) for safe cross-platform CI/CD
        var normalizedExpected = expected.Replace(WindowsLineEnding, UnixLineEnding).Replace("\r", UnixLineEnding);
        var normalizedActual = actual.Replace(WindowsLineEnding, UnixLineEnding).Replace("\r", UnixLineEnding);

        Assert.Equal(normalizedExpected, normalizedActual);
    }

    /// <summary>
    /// Verifies that two arrays of parameters match in length and sequence.
    /// </summary>
    /// <param name="expected">The expected array of parameter values.</param>
    /// <param name="actual">The actual array of parameter values extracted from the builder.</param>
    /// <exception cref="EqualException">Thrown when the parameters do not match.</exception>
    public static void MatchesParameters(object?[] expected, object?[] actual)
    {
        Assert.Equal(expected.Length, actual.Length);

        for (int i = 0; i < expected.Length; i++)
        {
            Assert.Equal(expected[i], actual[i]);
        }
    }
}