<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlInterpol\SqlInterpol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SqlInterpol.Testing.Xunit.targets" PackagePath="build\$(PackageId).targets" Pack="true" />
  </ItemGroup>

</Project>