using Xunit.Abstractions;

namespace SqlInterpol.Testing.Xunit;

/// <summary>
/// Represents a data-driven test case for SQL generation, encapsulating both the expected outcomes 
/// (SQL, parameters, or exceptions) and tracking the actual results generated during execution.
/// </summary>
public sealed class SqlTestCase : IXunitSerializable
{
    /// <summary>
    /// Gets a helper instance used to assert that the actual execution results match the expected state.
    /// </summary>
    public SqlTestCaseAssert Assert => new(this);
    
    /// <summary>
    /// Gets the list of actual SQL strings generated during the test execution.
    /// </summary>
    public List<string> ActualSql { get; } = [];

    /// <summary>
    /// Gets the list of actual parameter arrays generated during the test execution.
    /// </summary>
    public List<object?[]> ActualParametersList { get; } = [];

    /// <summary>
    /// Gets the list of exceptions thrown during the test execution.
    /// </summary>
    public List<Exception> ActualExceptions { get; } = [];
    
    /// <summary>
    /// Gets the type of the first exception thrown during execution, if any.
    /// </summary>
    public Type? ActualExceptionType => ActualExceptions.FirstOrDefault()?.GetType();

    /// <summary>
    /// Gets the array of expected SQL strings that should be generated by the operation.
    /// </summary>
    public string[]? ExpectedSql { get; private set; }

    /// <summary>
    /// Gets the expected parameters that should accompany the generated SQL.
    /// </summary>
    public object?[] ExpectedParameters { get; private set; } = [];

    /// <summary>
    /// Gets the type of exception expected to be thrown, typically for unsupported features or invalid syntax.
    /// </summary>
    public Type? ExpectedExceptionType { get; private set; }

    /// <summary>
    /// Gets the exact exception message expected to be thrown, if applicable.
    /// </summary>
    public string? ExpectedExceptionMessage { get; private set; }

    /// <summary>
    /// Gets the optional identifier used to label this test case in the xUnit Test Explorer.
    /// </summary>
    public string? Id { get; private set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="SqlTestCase"/> class. 
    /// Required for xUnit cross-AppDomain deserialization.
    /// </summary>
    public SqlTestCase() { }

    /// <summary>
    /// Initializes a new test case that expects a successful SQL string generation.
    /// </summary>
    /// <param name="expectedSql">The exact SQL string(s) expected to be generated.</param>
    /// <param name="expectedParameters">The parameters expected to be passed with the query.</param>
    /// <param name="id">An optional identifier for test runner UI display (e.g., the dialect name).</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="expectedSql"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="expectedSql"/> is empty.</exception>
    public SqlTestCase(string[] expectedSql, object?[]? expectedParameters = null, string? id = null)
    {
        ExpectedSql = expectedSql ?? throw new ArgumentNullException(nameof(expectedSql));
        if (expectedSql.Length == 0) throw new ArgumentException("ExpectedSql cannot be empty.", nameof(expectedSql));
        
        ExpectedParameters = expectedParameters ?? [];
        Id = id;
    }

    /// <summary>
    /// Initializes a new test case that expects an exception to be thrown (e.g., for an unsupported dialect feature).
    /// </summary>
    /// <param name="expectedExceptionType">The type of the expected exception.</param>
    /// <param name="expectedExceptionMessage">The exact message the exception should contain (optional).</param>
    /// <param name="id">An optional identifier for test runner UI display (e.g., the dialect name).</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="expectedExceptionType"/> is null.</exception>
    public SqlTestCase(Type expectedExceptionType, string? expectedExceptionMessage = null, string? id = null)
    {
        ExpectedExceptionType = expectedExceptionType ?? throw new ArgumentNullException(nameof(expectedExceptionType));
        ExpectedExceptionMessage = expectedExceptionMessage;
        Id = id;
    }

    /// <summary>
    /// Serializes the test case for xUnit theory execution.
    /// </summary>
    /// <param name="info">The serialization info object provided by xUnit.</param>
    public void Serialize(IXunitSerializationInfo info)
    {
        info.AddValue(nameof(ExpectedSql), ExpectedSql);
        info.AddValue(nameof(ExpectedExceptionType), ExpectedExceptionType?.AssemblyQualifiedName);
        info.AddValue(nameof(ExpectedExceptionMessage), ExpectedExceptionMessage);
        info.AddValue(nameof(ExpectedParameters), ExpectedParameters);
        info.AddValue(nameof(Id), Id);
    }

    /// <summary>
    /// Deserializes the test case during xUnit theory execution.
    /// </summary>
    /// <param name="info">The serialization info object provided by xUnit.</param>
    public void Deserialize(IXunitSerializationInfo info)
    {
        ExpectedSql = info.GetValue<string[]>(nameof(ExpectedSql));
        ExpectedParameters = info.GetValue<object?[]>(nameof(ExpectedParameters)) ?? [];

        var expectedExceptionTypeName = info.GetValue<string>(nameof(ExpectedExceptionType));
        if (!string.IsNullOrEmpty(expectedExceptionTypeName))
        {
            ExpectedExceptionType = Type.GetType(expectedExceptionTypeName);
        }

        ExpectedExceptionMessage = info.GetValue<string>(nameof(ExpectedExceptionMessage));
        Id = info.GetValue<string>(nameof(Id));
    }

    /// <summary>
    /// Returns a string that represents the current test case in the xUnit Test Explorer.
    /// </summary>
    /// <returns>The <see cref="Id"/> if provided; otherwise, "TestCase".</returns>
    public override string ToString()
    {
        return string.IsNullOrWhiteSpace(Id) ? "TestCase" : Id;
    }
}